### ISSUE TITLE
"Repository is gone" for Solidus core gems

### ISSUE THREAD

**Issue by aldesantis** [rubytoolbox/rubytoolbox#615] opened 2020-03-27 12:24 UTC
First of all, 👋 and thanks for this awesome tool! We're proud to sponsor it through [Ruby Together](https://rubytogether.org/).

I noticed all the core Solidus gems started indicating "Repository is gone", but the repository which contains them has never moved: https://github.com/solidusio/solidus.

Here are the affected projects:

- https://www.ruby-toolbox.com/projects/solidus_frontend
- https://www.ruby-toolbox.com/projects/solidus_api
- https://www.ruby-toolbox.com/projects/solidus_core
- https://www.ruby-toolbox.com/projects/solidus_sample
- https://www.ruby-toolbox.com/projects/solidus_backend
- https://www.ruby-toolbox.com/projects/solidus

Is this a bug and if so how can I help addressing the problem?

**Comment by colszowka** [comment] 2020-03-27 12:30
Hey there, thanks for the report! I suspect there is some issue in the sync mechanism. I will investigate and fix this over this weekend!

Best,
Christoph

**Comment by aldesantis** [comment] 2020-03-27 12:34
Sounds great, thanks @colszowka! Let me know if there's anything we can do on our side to help.

**Comment by colszowka** [comment] 2020-03-28 21:23
@aldesantis So I did a quick investigation, turns out the repo has landed on the ignore list, which is in place to not clog background workers with useless github repo references (there is a lot of those on "dead" rubygems):

* Ignore handler: https://github.com/rubytoolbox/rubytoolbox/blob/master/app/jobs/github_repo_update_job.rb#L76
* How the exception causing the ignore is issued: https://github.com/rubytoolbox/rubytoolbox/blob/master/app/services/github_client.rb#L33-L52

After removing the ignore and manually issuing the update the repos all went back into being reported correctly.

Looking closer at the second source link I suspect there was a temporary github outage on 24th, since there's 6k ignore records for that day, although Github status did not report anything for that day - https://www.githubstatus.com/

Regardless, at least 500-range errors should probably not make projects end up on the ignore list, and I will investigate a bit further if other cleanups might be neccessary.

I will keep this issue around regardless of the solidus-specific problem being solved because I want to also resolve this for any other potentially affected projects.

Thanks again for the report and be safe!

**Comment by skatkov** [comment] 2020-04-02 02:01
I was surprised to find my recent gem with a status "Repository is gone".

https://www.ruby-toolbox.com/projects/jekyll-news-sitemap

Seems like like a ran into same issue. I've randomly stumbled upon other projects I'm actively using, but marked as "repository is gone" recently. Unfortunately can't recall their names right now.

**Comment by colszowka** [comment] 2020-04-02 07:20
Yip, I am still on this, will investigate the root cause of the issue in the next days!

**Comment by copiousfreetime** [comment] 2020-04-02 16:15
@colszowka I just pushed a new version of htauth (after years of an old version existing) and now it is showing "long lived project that still receives updates"  - but it also says that the repository is gone - and the repository hasn't moved in more than 10 years :joy:

https://www.ruby-toolbox.com/projects/htauth

Since the long-lived badge just showed up - I'm assuming that those 2 statuses are synced in different manners. Hopefully that helps the debugging process. I updated the gemspec with the explicit `metadata['source_code_uri']` field, whereas before it was only using the `homepage` field.

Happy to help debug as needed - including looking at some code. If you have a pointer to a section of the codebase - happy to put another set of eyes on it.

 I have a few other gems that I could push with innocuous updates if that would help.

Checking on my other gems - repository is gone is now on:

* https://www.ruby-toolbox.com/projects/hitimes (last released 2019-09-23)
* https://www.ruby-toolbox.com/projects/torid (last released 2017-02-17)

Both of those gems do not have the metadata section in the gemspec - only the homepage setting.

**Comment by copiousfreetime** [comment] 2020-04-09 21:20
@colszowka just an FYI on this - although you are probably aware - it looks like every gem in ruby-toolbox.com is now marked as **Repository is gone**.

**Comment by colszowka** [comment] 2020-04-10 09:27
Hey there, yes, I am aware and will check it out very soon, there is still this glitch in the update mechanism and I didn't yet have the time to sit down and sort it out, but will do so in the next days!

**Comment by colszowka** [comment] 2020-04-18 20:28
Hey everyone, first of all thanks for your patience!

Via https://github.com/rubytoolbox/rubytoolbox/pull/649 I believe I have resolved the root cause of this, that led the data update system to put basically all repos on the ignore list and remove their references from projects, causing the "repository gone" badge to trigger.

I've force-queued updates for all projects with categories as well as the top 10000 projects by score that have a repo reference but no category. Those should slowly chug along over the next hours and get resolved (there is the github rate limit of 5000 hourly graphql calls so I cannot simply crank up workers temporarily and get the data in faster), but this should hopefully resolve itself entirely over the next day or so.

I will keep an eye on this as the data gets pulled back in, hopefully this is resolved now for good, sorry for the trouble!

**Comment by svoop** [comment] 2020-04-19 09:36
@colszowka Thanks a bunch for the fix! How about those projects without category and out of the top 10k (such as my [aixm](https://www.ruby-toolbox.com/projects/aixm), [aipp](https://www.ruby-toolbox.com/projects/aixm) or [ogn_client-ruby](https://www.ruby-toolbox.com/projects/ogn_client-ruby) – will there be a second pass for those?

**Comment by colszowka** [comment] 2020-04-19 09:46
@svoop Yes, all repos should eventually fully catch up again by themselves through the normal update mechanism, which periodically pulls all data every 1-2 days (again, this is bounded by API rate limits, 10 requests per second on rubygems and 5k per hour on GitHub, I think we have currently around 160k gems and 100k of those have GitHub references), but I will also keep an eye on this myself a bit to ensure to give it a gentle push in case things don't catch up by themselves.

Please also consider submitting your aeronautics projects (and others you might know) into a new category, this seems like an interesting use of ruby :)

**Comment by svoop** [comment] 2020-04-19 09:48
@colszowka 

> Please also consider submitting your aeronautics projects (and others you might know) into a new category, this seems like an interesting use of ruby :)

Wilco 😉 Thanks again for the fix and for maintaining the toolbox!

**Comment by colszowka** [comment] 2020-04-19 19:31
Ok, so I checked up on the current state of things, we're at ~85k repos linked again against ~160k projects. 25k projects have repo references on the gem but no repo link yet, but plenty of those at this point will be coming from actually missing repos.

For the projects mentioned above by @svoop 2 had already resolved themselves through the daily update process, one of them I gave a little push and it's also synced now. I think any missing projects should resolve themselves soon as well, and I deem this issue closed but will keep an eye if there is any further regression over the next days.

Take care everyone!

**Closed** 2020-04-19 20:25 UTC
Labels: bug
